release now fails when tests do the same

diff --git a/release b/release
--- a/release
+++ b/release
@@ -67,7 +67,11 @@ for i in ./locale/*; do
     $EDITOR $popath
     msgfmt -o $podir/pkgbuilder.mo $popath
 done
-
+./tests.py
+if [[ $? = 1 ]]; then
+    echo "Tests failed.  Fix your code or don't come back."
+    exit 1
+fi
 ./setup.py sdist upload
 
 md5out=$(md5sum 'dist/'$project'-'$version'.tar.gz'|awk '{print $1}')
